// MedSchool Prep — Complete Quiz Bank
// Answer keys are deliberately varied: A=0, B=1, C=2, D=3
// Each quiz: 8 challenging questions, MCAT-level difficulty

export const QUIZ_BANK = {
  biochemistry: [
    {
      id:"bio_001", title:"Glycolysis & Regulation", difficulty:"Hard", time:480, icon:"🧪",
      questions:[
        { q:"Which enzyme catalyzes the rate-limiting, irreversible commitment step of glycolysis?",
          choices:["Hexokinase","Phosphofructokinase-1","Pyruvate kinase","Phosphoglucose isomerase"], correct:1,
          exp:"PFK-1 is the main pacemaker of glycolysis. Allosterically inhibited by ATP and citrate, activated by AMP and fructose-2,6-bisphosphate. This is the major regulated step." },
        { q:"Arsenate poisoning uncouples substrate-level phosphorylation in glycolysis because it:",
          choices:["Inhibits PFK-1 directly","Substitutes for phosphate forming an unstable 1-arseno-3-PG","Blocks GAPDH irreversibly","Chelates NAD⁺"], correct:1,
          exp:"Arsenate replaces inorganic phosphate in the GAPDH reaction, forming 1-arseno-3-phosphoglycerate, which spontaneously hydrolyzes — bypassing ATP synthesis." },
        { q:"In the Cori cycle, glucose produced by the liver is derived from:",
          choices:["Alanine exported by hepatocytes","Lactate exported by erythrocytes and muscle","Glycogen stored in skeletal muscle","Gluconeogenesis from fatty acids"], correct:1,
          exp:"The Cori cycle converts lactate (from anaerobic muscle/RBC glycolysis) to glucose in the liver via gluconeogenesis, recycling carbon at an ATP cost to the liver." },
        { q:"Net ATP yield from complete glycolysis of one glucose molecule (cytoplasm only) is:",
          choices:["4 ATP","1 ATP","2 ATP","8 ATP"], correct:2,
          exp:"Glycolysis produces 4 ATP gross but invests 2 ATP in the preparatory phase, for a net gain of 2 ATP per glucose." },
        { q:"Pyruvate kinase deficiency in erythrocytes most directly causes:",
          choices:["Polycythemia vera","Hemolytic anemia due to ATP depletion","Methemoglobinemia","Thrombocytosis"], correct:1,
          exp:"RBCs rely entirely on glycolysis for ATP. PK deficiency reduces ATP, impairing ion pumps, causing rigid cells destroyed in the spleen — hemolytic anemia." },
        { q:"Fructose-2,6-bisphosphate simultaneously stimulates PFK-1 and inhibits FBPase-1 to:",
          choices:["Block both glycolysis and gluconeogenesis","Activate glycolysis and inhibit gluconeogenesis reciprocally","Activate gluconeogenesis only","Inhibit both pathways during fasting"], correct:1,
          exp:"F-2,6-BP is the most potent allosteric activator of PFK-1 and simultaneously inhibits FBPase-1, ensuring reciprocal regulation of glycolysis vs. gluconeogenesis." },
        { q:"Which molecule directly donates a phosphate to ADP during substrate-level phosphorylation in glycolysis?",
          choices:["NADH","Phosphoenolpyruvate","Fructose-1,6-bisphosphate","Glucose-6-phosphate"], correct:1,
          exp:"PEP is converted to pyruvate by pyruvate kinase, transferring its high-energy phosphate to ADP, forming ATP via substrate-level phosphorylation." },
        { q:"During the preparatory phase of glycolysis, the phosphorylation of fructose-6-phosphate by PFK-1 is irreversible and consumes:",
          choices:["2 ATP total in this step","1 ATP to form fructose-1,6-bisphosphate","GTP rather than ATP","NADPH as the phosphate donor"], correct:1,
          exp:"PFK-1 uses 1 ATP to phosphorylate fructose-6-phosphate to fructose-1,6-bisphosphate. This is the second ATP investment (the first was hexokinase) in the preparatory phase." },
      ]
    },
    {
      id:"bio_002", title:"TCA Cycle & Electron Transport", difficulty:"Hard", time:480, icon:"⚡",
      questions:[
        { q:"Which TCA cycle enzyme is embedded in the inner mitochondrial membrane rather than the matrix?",
          choices:["Isocitrate dehydrogenase","α-Ketoglutarate dehydrogenase","Succinate dehydrogenase","Fumarase"], correct:2,
          exp:"Succinate dehydrogenase (Complex II) is the only TCA enzyme in the IMM. It feeds electrons into the ETC via FADH₂ without pumping protons." },
        { q:"How many NADH molecules are produced per acetyl-CoA entering the TCA cycle?",
          choices:["2","4","3","6"], correct:2,
          exp:"Three NADH are produced: at isocitrate dehydrogenase, α-ketoglutarate dehydrogenase, and malate dehydrogenase steps." },
        { q:"Thiamine (B1) deficiency impairs the TCA cycle primarily by inhibiting:",
          choices:["Citrate synthase","α-Ketoglutarate dehydrogenase and pyruvate dehydrogenase","Succinyl-CoA synthetase","Malate dehydrogenase"], correct:1,
          exp:"Both PDH and α-KGDH require thiamine pyrophosphate (TPP). B1 deficiency blocks these steps → pyruvate and α-KG accumulation → Wernicke's encephalopathy." },
        { q:"Cyanide poisoning kills by blocking:",
          choices:["Complex I","ATP synthase","Complex IV (cytochrome c oxidase)","Ubiquinone"], correct:2,
          exp:"CN⁻ binds Fe³⁺ in cytochrome a₃ of Complex IV, blocking O₂ reduction and completely halting the ETC. Cells cannot produce ATP aerobically." },
        { q:"Which intermediate is shared between the TCA cycle and the urea cycle?",
          choices:["Oxaloacetate","Citrate","Fumarate","Succinyl-CoA"], correct:2,
          exp:"Fumarate is produced in the urea cycle (from argininosuccinate) and enters the TCA cycle in mitochondria, linking nitrogen disposal and energy metabolism." },
        { q:"GTP produced in the TCA cycle is generated at which step?",
          choices:["Citrate synthase","Isocitrate dehydrogenase","Succinyl-CoA synthetase","Malate dehydrogenase"], correct:2,
          exp:"Succinyl-CoA synthetase converts succinyl-CoA to succinate with coupled GDP→GTP phosphorylation (substrate-level phosphorylation). GTP ≈ ATP energetically." },
        { q:"Uncouplers like 2,4-dinitrophenol cause weight loss by:",
          choices:["Inhibiting ATP synthase directly","Dissipating the proton gradient as heat without making ATP","Blocking Complex I","Activating lipase in adipocytes"], correct:1,
          exp:"DNP is a lipophilic weak acid that shuttles H⁺ across the IMM, collapsing the proton gradient and releasing energy as heat. The ETC runs at maximum rate without making ATP." },
        { q:"The modern P/O ratio for NADH oxidation via the ETC is approximately:",
          choices:["1.0","3.5","2.5","4.0"], correct:2,
          exp:"Modern measurements give P/O ≈ 2.5 for NADH (10 H⁺ pumped, ~4 H⁺ per ATP → 10/4 ≈ 2.5 ATP per NADH). Older textbooks used 3; MCAT uses ~2.5." },
      ]
    },
    {
      id:"bio_003", title:"Amino Acid Metabolism", difficulty:"Hard", time:480, icon:"🔬",
      questions:[
        { q:"Phenylketonuria (PKU) results from deficiency of:",
          choices:["Tyrosinase","Homogentisate oxidase","Phenylalanine hydroxylase","Cystathionine synthase"], correct:2,
          exp:"PAH converts phenylalanine to tyrosine using BH4. Its deficiency causes phenylalanine accumulation → toxic metabolites that impair CNS myelination." },
        { q:"Which amino acid is purely ketogenic (cannot contribute to gluconeogenesis)?",
          choices:["Isoleucine","Phenylalanine","Leucine","Tyrosine"], correct:2,
          exp:"Leucine is degraded entirely to acetyl-CoA and acetoacetate — both purely ketogenic. Isoleucine and phenylalanine are both glucogenic AND ketogenic." },
        { q:"Maple syrup urine disease involves accumulation of which amino acids?",
          choices:["Phenylalanine, tyrosine, tryptophan","Leucine, isoleucine, valine","Methionine, cysteine, homocysteine","Lysine, arginine, ornithine"], correct:1,
          exp:"MSUD is caused by deficiency of branched-chain α-keto acid dehydrogenase (requires B1), impairing catabolism of leucine, isoleucine, and valine." },
        { q:"The transamination reaction catalyzed by AST uses which coenzyme?",
          choices:["NAD⁺","Thiamine pyrophosphate","Pyridoxal phosphate","Biotin"], correct:2,
          exp:"Aminotransferases (ALT, AST) all use PLP (vitamin B6) to shuttle amino groups from amino acids to α-ketoglutarate, forming glutamate. PLP forms a Schiff base with the substrate." },
        { q:"Serotonin is synthesized from which amino acid precursor?",
          choices:["Phenylalanine","Histidine","Tryptophan","Tyrosine"], correct:2,
          exp:"Tryptophan → 5-hydroxytryptophan (via tryptophan hydroxylase, requiring BH4) → serotonin. Tryptophan also generates NAD⁺ via the kynurenine pathway." },
        { q:"Which enzyme deficiency causes oculocutaneous albinism?",
          choices:["Phenylalanine hydroxylase","Tyrosinase","Homogentisate oxidase","Fumarylacetoacetate hydrolase"], correct:1,
          exp:"Tyrosinase converts tyrosine to DOPA and dopaquinone in melanocytes, initiating melanin synthesis. Its absence causes oculocutaneous albinism." },
        { q:"Homocystinuria from CBS deficiency is treated with high-dose B6 because:",
          choices:["B6 increases CBS expression via transcription","PLP is a required cofactor for CBS and some mutations retain partial B6-responsive activity","B6 inhibits homocysteine remethylation","Pyridoxal increases folate absorption"], correct:1,
          exp:"CBS requires PLP (B6 active form). Some mutations retain partial enzyme activity responsive to PLP supplementation, making high-dose B6 the first-line treatment." },
        { q:"One-carbon transfer reactions requiring tetrahydrofolate (THF) are critical for synthesis of:",
          choices:["Lysine and threonine","Purines and thymidylate","Cholesterol and ceramide","Heme and cobalamin"], correct:1,
          exp:"THF carries one-carbon units needed for purine ring synthesis (C2, C8) and converting dUMP→dTMP via thymidylate synthase. This is why folate deficiency causes megaloblastic anemia." },
      ]
    },
    {
      id:"bio_004", title:"Enzyme Kinetics & Inhibition", difficulty:"Hard", time:480, icon:"📊",
      questions:[
        { q:"A competitive inhibitor increases Km while Vmax remains unchanged because:",
          choices:["It covalently modifies the active site permanently","It competes with substrate for the active site and can be overcome by excess substrate","It binds an allosteric site reducing catalytic rate","It increases the activation energy"], correct:1,
          exp:"Competitive inhibitors bind the active site reversibly. High [S] displaces the inhibitor, restoring Vmax. Apparent Km increases because more substrate is needed to achieve half-maximal velocity." },
        { q:"Kcat (turnover number) is defined as:",
          choices:["The substrate concentration giving half-maximal velocity","The number of substrate molecules converted per enzyme per second at saturation","The rate constant for ES complex formation","The ratio of catalytic rate to total enzyme at low [S]"], correct:1,
          exp:"Kcat = Vmax / [E]total. It represents maximum catalytic events per enzyme per second at saturating substrate. Higher Kcat = faster enzyme when saturated." },
        { q:"The Hill coefficient (n) for hemoglobin oxygen binding (~2.8) indicates:",
          choices:["Hemoglobin has 2.8 oxygen binding sites","Negative cooperativity between subunits","Positive cooperativity — binding of O₂ increases affinity for subsequent O₂","The T-state has 2.8× higher affinity than the R-state"], correct:2,
          exp:"A Hill coefficient > 1 indicates positive cooperativity. For Hb, binding of the first O₂ causes T→R conformational change, increasing O₂ affinity in remaining subunits." },
        { q:"Feedback inhibition of ATCase by CTP is an example of:",
          choices:["Competitive inhibition","Allosteric regulation","Covalent modification","Zymogen activation"], correct:1,
          exp:"CTP (end-product of pyrimidine synthesis) allosterically inhibits ATCase (early step), preventing overproduction. Classic end-product feedback allosteric inhibition." },
        { q:"Which statement about uncompetitive inhibition is true?",
          choices:["Inhibitor binds free enzyme only","Both Km and Vmax decrease proportionally","Vmax decreases but Km is unchanged","Lineweaver-Burk shows lines intersecting on the x-axis"], correct:1,
          exp:"Uncompetitive inhibitors bind only the ES complex, pulling equilibrium toward ES formation (apparent Km decreases) while reducing Vmax. L-B plot shows parallel lines." },
        { q:"An irreversible inhibitor covalently modifying the active site appears on a Lineweaver-Burk plot as:",
          choices:["Same x-intercept (same -1/Km), higher y-intercept (lower Vmax)","Lines intersecting on the y-axis","Lines with same slope, different y-intercepts","No change in either intercept"], correct:0,
          exp:"Irreversible inhibition reduces functional enzyme concentration, decreasing Vmax without changing Km. Same x-intercept (-1/Km), higher y-intercept (higher 1/Vmax)." },
        { q:"Statins inhibit HMG-CoA reductase acting as which type of inhibitor?",
          choices:["Uncompetitive inhibitor","Competitive inhibitor (statin mimics mevalonate transition state)","Irreversible inhibitor","Mixed inhibitor"], correct:1,
          exp:"Statins are structural analogs of the HMG-CoA/mevalonate transition state, competitively binding the active site. LDL uptake by liver cells increases as compensation." },
        { q:"The catalytic efficiency of an enzyme is best measured by:",
          choices:["Vmax alone","Km alone","Kcat/Km (specificity constant)","Kcat alone at all substrate concentrations"], correct:2,
          exp:"Kcat/Km is the second-order rate constant for the enzyme-substrate encounter and reflects catalytic efficiency at low [S] — the best single measure of how efficiently an enzyme converts substrate to product." },
      ]
    },
    {
      id:"bio_005", title:"DNA Replication & Repair", difficulty:"Hard", time:480, icon:"🧬",
      questions:[
        { q:"Okazaki fragments on the lagging strand are joined by:",
          choices:["DNA Pol I only","DNA ligase after RNA primer removal by DNA Pol I","Primase and DNA Pol III together","Topoisomerase II"], correct:1,
          exp:"DNA Pol I removes the RNA primer and replaces it with DNA (5'→3' polymerase + 5'→3' exonuclease). DNA ligase then seals the nick between adjacent Okazaki fragments." },
        { q:"The enzyme that relieves positive supercoiling ahead of the replication fork is:",
          choices:["Helicase","DNA Pol III","Topoisomerase I","Primase"], correct:2,
          exp:"As helicase unwinds the double helix, positive supercoils build up ahead. Topoisomerase I nicks one strand, allows rotation, and religates — relaxing the supercoiled DNA." },
        { q:"PCNA functions as a:",
          choices:["Proofreading exonuclease","Sliding clamp for DNA polymerase δ","Helicase at origins","Mismatch recognition protein"], correct:1,
          exp:"PCNA forms a homotrimeric ring (sliding clamp) that encircles DNA and tethers DNA Pol δ, dramatically increasing its processivity during eukaryotic synthesis." },
        { q:"Which repair mechanism corrects thymine dimers caused by UV radiation?",
          choices:["Mismatch repair","Base excision repair","Nucleotide excision repair","Translesion synthesis"], correct:2,
          exp:"NER recognizes bulky helix-distorting lesions like thymine dimers. A ~30-nucleotide segment containing the lesion is excised; DNA Pol fills in using the intact strand." },
        { q:"Lynch syndrome (HNPCC) involves germline mutations in:",
          choices:["BRCA1/BRCA2","MLH1/MSH2 (mismatch repair genes)","TP53","ATM/CHEK2"], correct:1,
          exp:"Lynch syndrome is caused by mutations in mismatch repair genes (MLH1, MSH2, MSH6, PMS2). MMR deficiency allows replication errors at microsatellites → microsatellite instability (MSI-H)." },
        { q:"The 3'→5' exonuclease activity of DNA polymerase III provides:",
          choices:["Primer removal","Nick translation","Proofreading (error correction)","Strand displacement synthesis"], correct:2,
          exp:"The 3'→5' exonuclease (proofreading) activity of DNA Pol III excises incorrectly incorporated nucleotides, reducing the error rate from ~1:10⁵ to ~1:10⁷ before mismatch repair." },
        { q:"RFC (Replication Factor C) functions as a:",
          choices:["Unwinds DNA at the origin","Clamp loader — uses ATP to load PCNA onto DNA","Synthesizes the RNA primer","Removes histones ahead of the fork"], correct:1,
          exp:"RFC is the clamp loader: it uses ATP hydrolysis to open and load PCNA onto the primer-template junction, enabling processive synthesis by DNA Pol δ." },
        { q:"Xeroderma pigmentosum patients are highly susceptible to UV-induced skin cancer because of defects in:",
          choices:["Telomerase activity","Base excision repair","Homologous recombination","Nucleotide excision repair proteins (XPA–XPG)"], correct:3,
          exp:"XP results from mutations in NER proteins. Without NER, thymine dimers accumulate in skin cell DNA, causing mutations in tumor suppressors and proto-oncogenes." },
      ]
    },
    {
      id:"bio_006", title:"Lipid Metabolism", difficulty:"Hard", time:480, icon:"💧",
      questions:[
        { q:"The rate-limiting enzyme of de novo fatty acid synthesis is:",
          choices:["Fatty acid synthase","Malonyl-CoA decarboxylase","Acetyl-CoA carboxylase","Citrate lyase"], correct:2,
          exp:"ACC carboxylates acetyl-CoA → malonyl-CoA, requiring biotin and ATP. Activated by citrate; inhibited by palmitoyl-CoA (product feedback) and glucagon-stimulated phosphorylation." },
        { q:"During β-oxidation of an 18-carbon saturated fatty acid, how many acetyl-CoA are produced?",
          choices:["8","10","9","16"], correct:2,
          exp:"An 18-carbon FA undergoes 8 rounds of β-oxidation to yield 9 acetyl-CoA. Each cycle shortens the chain by 2 carbons. (18÷2 = 9 acetyl-CoA; 8 cycles needed.)" },
        { q:"Ketone bodies are produced in which organ and under which condition?",
          choices:["Muscle during aerobic exercise","Liver during prolonged fasting/starvation","Adipose tissue during lipolysis","Brain during glucose excess"], correct:1,
          exp:"Ketogenesis occurs in hepatic mitochondria when acetyl-CoA exceeds TCA capacity (OAA depleted for gluconeogenesis). β-Hydroxybutyrate and acetoacetate are exported as fuel." },
        { q:"Malonyl-CoA inhibits carnitine acyltransferase I because:",
          choices:["It competes with carnitine for the binding site","It signals FA synthesis is active, preventing futile FA import for β-oxidation","It directly inhibits the TCA cycle","It depletes mitochondrial NAD⁺"], correct:1,
          exp:"Malonyl-CoA (first committed intermediate in FA synthesis) inhibits CPT-I, preventing fatty acids from entering mitochondria for β-oxidation when synthesis is active. Prevents a futile cycle." },
        { q:"Which lipoprotein delivers dietary lipids from intestine to peripheral tissues?",
          choices:["VLDL","LDL","Chylomicrons","HDL"], correct:2,
          exp:"Chylomicrons are assembled in intestinal enterocytes, secreted into lymph → thoracic duct → blood. LPL on capillary endothelium releases FA; chylomicron remnants go to liver." },
        { q:"Essential fatty acids must be consumed because humans lack:",
          choices:["Elongases for chain extension beyond C16","Δ12 and Δ15 desaturases","Lipoxygenase enzymes","Phospholipase A2"], correct:1,
          exp:"Humans can desaturate at Δ9 (SCD) but cannot introduce double bonds at Δ12 or Δ15 (ω-6 and ω-3 positions). Plants have these desaturases." },
        { q:"Abetalipoproteinemia causes fat malabsorption because patients cannot synthesize:",
          choices:["LDL receptors","Apolipoprotein B (apoB-48 and apoB-100)","Bile salts","Pancreatic lipase"], correct:1,
          exp:"ApoB is required to assemble and secrete chylomicrons (apoB-48) and VLDL (apoB-100). Without apoB, dietary fat and fat-soluble vitamins cannot be transported." },
        { q:"The reducing agents required for de novo fatty acid synthesis are:",
          choices:["NADH and FADH₂","NADPH (from PPP and malic enzyme)","Both NADPH and NADH equally","ATP and NADPH"], correct:1,
          exp:"Fatty acid synthesis requires 2 NADPH per elongation cycle (for KR and ER domain reductions in FAS). NADPH comes from the pentose phosphate pathway and malic enzyme." },
      ]
    },
  ],

  physiology: [
    {
      id:"physio_001", title:"Cardiovascular Physiology", difficulty:"Hard", time:480, icon:"❤️",
      questions:[
        { q:"The Frank-Starling mechanism states that stroke volume increases when:",
          choices:["Heart rate increases proportionally","Preload (EDV) increases, stretching sarcomeres to optimal length","Afterload decreases","Sympathetic stimulation increases intracellular Ca²⁺"], correct:1,
          exp:"Increased venous return → greater EDV (preload) → sarcomere stretch → optimized actin-myosin overlap → increased force → increased stroke volume. Intrinsic property allowing heart to match output to venous return." },
        { q:"The QRS complex in an ECG represents:",
          choices:["Atrial depolarization","Ventricular depolarization initiating ventricular contraction","Ventricular repolarization","AV node conduction delay"], correct:1,
          exp:"ECG: P wave = atrial depolarization; PR interval = AV node delay; QRS = ventricular depolarization; T wave = ventricular repolarization. Atrial repolarization is hidden within the QRS." },
        { q:"Which coronary artery is most commonly affected in anterior STEMI?",
          choices:["Right coronary artery (RCA)","Left circumflex artery (LCx)","Left anterior descending artery (LAD)","Posterior descending artery (PDA)"], correct:2,
          exp:"The LAD supplies the anterior wall, apex, and anterior 2/3 of the interventricular septum. LAD occlusion → anterior STEMI (ST elevation V1-V4)." },
        { q:"Atrial natriuretic peptide (ANP) released during atrial stretch causes:",
          choices:["Vasoconstriction and increased aldosterone secretion","Vasodilation, increased GFR, inhibition of aldosterone, and natriuresis","Increased ADH release from posterior pituitary","Decreased renin release with compensatory water retention"], correct:1,
          exp:"ANP causes afferent arteriole dilation + efferent constriction → increased GFR; natriuresis; inhibits RAAS; inhibits ADH. Net effect: reduces blood volume and blood pressure." },
        { q:"The refractory period of cardiac muscle is much longer than skeletal muscle because:",
          choices:["Cardiac muscle has fewer voltage-gated Na⁺ channels","The long plateau phase (Phase 2, L-type Ca²⁺ channels) keeps membrane depolarized, preventing premature re-excitation","Cardiac muscle lacks T-tubules","The SA node continuously suppresses premature ventricular contractions"], correct:1,
          exp:"Cardiac AP plateau (phase 2): L-type Ca²⁺ channels maintain depolarization ~200-300ms. This extended refractory period prevents tetanus and allows AV node to regulate ventricular rate." },
        { q:"In hypovolemic shock, the baroreceptor reflex compensates by:",
          choices:["Decreasing heart rate and vasodilating","Increasing heart rate and causing vasoconstriction to maintain MAP","Releasing ANP to increase preload","Stimulating aldosterone to immediately restore volume"], correct:1,
          exp:"Decreased MAP → decreased baroreceptor firing → increased sympathetic + decreased parasympathetic → tachycardia, vasoconstriction, increased contractility. Rapidly compensates MAP = CO × SVR." },
        { q:"During exercise, skeletal muscle blood flow dramatically increases due to:",
          choices:["Systemic vasodilation by ANP","Local metabolic vasodilation (CO₂, H⁺, adenosine, K⁺) overriding sympathetic vasoconstriction","Increased cardiac output alone redistributing fixed blood flow","Decrease in blood viscosity from exercise-induced anemia"], correct:1,
          exp:"Local metabolites (CO₂↑, O₂↓, H⁺↑, K⁺↑, adenosine↑, heat↑) cause arteriolar vasodilation in active muscle, dramatically increasing local blood flow. Functional hyperemia." },
        { q:"The pulse pressure is the difference between systolic and diastolic pressure. It increases in:",
          choices:["Hypovolemic shock (narrows)","Aortic regurgitation (widened pulse pressure due to large stroke volume + rapid diastolic run-off)","Cardiac tamponade (narrows/paradoxus)","Severe aortic stenosis (narrowed due to reduced SV)"], correct:1,
          exp:"Aortic regurgitation: regurgitant flow increases SV → high systolic pressure; diastolic back-flow reduces diastolic pressure. Wide pulse pressure (bounding/water-hammer pulse) is classic. Systolic HTN in elderly also widens PP due to arterial stiffness." },
      ]
    },
    {
      id:"physio_002", title:"Pulmonary Physiology", difficulty:"Hard", time:480, icon:"🫁",
      questions:[
        { q:"The O₂-Hb dissociation curve shifts RIGHT under which conditions?",
          choices:["Decreased temperature, decreased 2,3-DPG, increased pH","Increased temperature, increased 2,3-DPG, increased PCO₂, decreased pH","Decreased PCO₂, alkalosis, fetal hemoglobin","Increased Hb-O₂ affinity at the alveolus"], correct:1,
          exp:"Right shift (Bohr effect) = decreased Hb-O₂ affinity = facilitates O₂ unloading in tissues. Causes: ↑T°, ↑CO₂, ↓pH (acidosis), ↑2,3-DPG. All increase in exercising muscle." },
        { q:"Type II pneumocytes are important because they:",
          choices:["Perform gas exchange across the alveolar-capillary membrane","Produce surfactant and regenerate the alveolar epithelium after injury","Line the bronchioles and prevent infection","Phagocytose foreign particles in the alveolar lumen"], correct:1,
          exp:"Type II pneumocytes produce surfactant (primarily DPPC) and are the stem cells of the alveolar epithelium — they proliferate and differentiate into type I cells after injury." },
        { q:"Spirometry shows FEV1/FVC = 62% and FEV1 improves >12% after bronchodilator. This indicates:",
          choices:["Restrictive lung disease","Obstructive lung disease with significant reversibility (asthma)","Mixed obstructive-restrictive disease","Normal spirometry for a 70-year-old"], correct:1,
          exp:"Obstructive: FEV1/FVC < 70%. Significant bronchodilator reversibility (>12% and >200mL FEV1 increase) = reversible obstruction = asthma (vs. COPD with minimal reversibility)." },
        { q:"Hypoxic pulmonary vasoconstriction (HPV) serves to:",
          choices:["Increase blood flow to hypoxic alveoli to improve gas exchange","Divert blood away from poorly ventilated alveoli to better-ventilated regions, optimizing V/Q matching","Increase pulmonary arterial pressure to recruit apical vessels","Stimulate type II pneumocytes to increase surfactant production"], correct:1,
          exp:"HPV: local alveolar hypoxia causes smooth muscle contraction in adjacent arterioles, diverting blood to better-ventilated areas and improving V/Q matching. Unique among vascular beds (opposite of systemic response)." },
        { q:"CO₂ is transported in blood primarily as:",
          choices:["Dissolved CO₂ in plasma (~10%)","Carbaminohemoglobin (~20-25%)","Bicarbonate ion (HCO₃⁻, ~70%) formed in RBCs via carbonic anhydrase","Equal amounts of all three forms"], correct:2,
          exp:"CO₂ transport: ~70% as HCO₃⁻ (via carbonic anhydrase in RBCs + chloride shift); ~20-25% as carbaminohemoglobin; ~5-10% dissolved in plasma." },
        { q:"In a patient with COPD and chronic hypercapnia, the primary drive to breathe becomes:",
          choices:["Central chemoreceptors responding to CO₂ (normal drive remains)","Hypoxic drive via peripheral chemoreceptors (central receptors adapted to chronically elevated CO₂)","Decreased pulmonary stretch receptor input","Elevated bicarbonate levels stimulating the medullary center"], correct:1,
          exp:"In chronic hypercapnia, the brain adapts (increases HCO₃⁻ to normalize pH) → central chemoreceptors desensitized → ventilation driven by hypoxia via carotid and aortic bodies. High-flow O₂ removes hypoxic drive → respiratory depression." },
        { q:"A-a gradient is elevated (>15 mmHg) in all of the following EXCEPT:",
          choices:["V/Q mismatch (e.g., pulmonary embolism)","Right-to-left shunt","Diffusion impairment (pulmonary fibrosis)","Pure hypoventilation (e.g., opioid overdose)"], correct:3,
          exp:"Pure hypoventilation increases PaCO₂ and decreases PaO₂, but the alveolar-arterial O₂ gradient remains NORMAL because the alveolar gas equation accounts for the CO₂ displacement of O₂. The lungs are not the problem — the ventilatory drive is." },
        { q:"Surfactant deficiency in premature infants (NRDS) causes respiratory failure because, by Laplace's Law (P = 2γ/r):",
          choices:["Larger alveoli collapse more easily without surfactant","Smaller alveoli have higher collapsing pressure without surfactant to reduce surface tension; they empty into larger alveoli","Surfactant deficiency increases pulmonary blood flow causing flooding","DPPC is needed for gas exchange directly"], correct:1,
          exp:"Laplace: P = 2γ/r. Smaller alveoli have higher collapsing pressure. Surfactant normally reduces γ as alveoli shrink, stabilizing them. Without surfactant, small alveoli collapse (atelectasis) → shunt → hypoxia." },
      ]
    },
    {
      id:"physio_003", title:"Renal Physiology", difficulty:"Hard", time:480, icon:"🫘",
      questions:[
        { q:"ADH (vasopressin) increases water reabsorption by:",
          choices:["Activating Na-K-2Cl cotransporter in the thick ascending limb","Inserting aquaporin-2 (AQP2) water channels into the apical membrane via V2-cAMP-PKA pathway","Stimulating aldosterone release from adrenal cortex","Directly increasing Na⁺ reabsorption in the proximal tubule"], correct:1,
          exp:"ADH → V2 receptors → Gs → adenylyl cyclase → cAMP → PKA → phosphorylation of AQP2 vesicles → insertion into apical membrane → water reabsorption. SIADH = excess ADH → dilutional hyponatremia." },
        { q:"A patient has metabolic acidosis with a normal anion gap. The most likely cause is:",
          choices:["Diabetic ketoacidosis","Lactic acidosis","Diarrhea (loss of HCO₃⁻) or renal tubular acidosis","Ethylene glycol toxicity"], correct:2,
          exp:"Normal AG acidosis: HCO₃⁻ is lost and replaced by Cl⁻ (hyperchloremic metabolic acidosis). Causes: diarrhea (GI HCO₃⁻ loss), RTA. High AG acidosis (DKA, lactic acidosis, toxins): unmeasured anions accumulate." },
        { q:"Aldosterone acts on principal cells of the collecting duct to:",
          choices:["Insert aquaporin-2 channels into the apical membrane","Increase apical ENaC and basolateral Na⁺/K⁺-ATPase expression, promoting Na⁺ reabsorption and K⁺ secretion","Stimulate intercalated cells to secrete H⁺","Inhibit Na⁺ reabsorption to lower blood pressure"], correct:1,
          exp:"Aldosterone binds intracellular receptors → SGK1 → increased ENaC in apical membrane + Na⁺/K⁺-ATPase basolaterally → Na⁺ reabsorption + K⁺ secretion. Hyperaldosteronism → hypertension, hypokalemia." },
        { q:"The loop of Henle creates the medullary concentration gradient via:",
          choices:["Active water reabsorption in the thin descending limb","Countercurrent multiplication: TALH actively transports NaCl without water, concentrating medulla, driving water from thin descending limb","Urea recycling from collecting duct into thin ascending limb only","Passive NaCl reabsorption in the thin descending limb only"], correct:1,
          exp:"TALH: Na-K-2Cl transport (target of loop diuretics) with no water permeability → NaCl absorbed, medulla concentrated. Thin descending limb: permeable to water → water flows out → tubular fluid becomes hyperosmotic." },
        { q:"Starling forces govern fluid movement across capillaries. Edema results from all of the following EXCEPT:",
          choices:["Increased capillary hydrostatic pressure (heart failure)","Decreased plasma oncotic pressure (nephrotic syndrome)","Increased lymphatic drainage","Increased capillary permeability (inflammation)"], correct:2,
          exp:"Edema = net filtration exceeds lymphatic drainage. Causes: ↑capillary hydrostatic pressure; ↓plasma oncotic pressure; ↑capillary permeability; lymphatic obstruction. INCREASED lymphatic drainage would PREVENT edema." },
        { q:"GFR is measured clinically using creatinine clearance because creatinine is:",
          choices:["Filtered and reabsorbed in equal amounts","Freely filtered and not reabsorbed, with minimal tubular secretion at normal levels","Actively secreted to double its filtered load","Bound to plasma proteins and not filtered at all"], correct:1,
          exp:"Creatinine is freely filtered at the glomerulus, not reabsorbed, with minimal secretion at normal levels. Thus creatinine clearance ≈ GFR. (At high serum creatinine, tubular secretion becomes more significant, leading to overestimation of GFR.)" },
        { q:"SIADH (syndrome of inappropriate ADH) most directly causes:",
          choices:["Hypernatremia and concentrated urine","Hyponatremia and inappropriately concentrated urine despite low serum osmolality","Hyperkalemia from reduced aldosterone","Nephrogenic diabetes insipidus"], correct:1,
          exp:"SIADH: excess ADH → water reabsorption despite low serum osmolality → dilutional hyponatremia. Urine is inappropriately concentrated (>100 mOsm/kg) when it should be dilute. Urine Na⁺ > 40 mEq/L." },
        { q:"A patient with uncontrolled hypertension and GFR = 40 mL/min would have serum creatinine approximately:",
          choices:["0.9 mg/dL (normal)","1.8 mg/dL","3.6 mg/dL","0.5 mg/dL"], correct:1,
          exp:"Normal GFR ~120 mL/min, normal creatinine ~0.9 mg/dL. GFR 40 mL/min ≈ 1/3 normal → creatinine roughly triples (nonlinear inverse relationship) ≈ 1.8-2.5 mg/dL. Early CKD missed if creatinine alone is used." },
      ]
    },
    {
      id:"physio_004", title:"Neurophysiology", difficulty:"Hard", time:480, icon:"🧠",
      questions:[
        { q:"The resting membrane potential (~-70 mV) is primarily maintained by:",
          choices:["Na⁺/K⁺-ATPase directly generating the potential","High K⁺ permeability at rest allowing K⁺ efflux, leaving negative charges inside","High Cl⁻ impermeability maintaining negative interior","Na⁺ influx through voltage-gated channels at rest"], correct:1,
          exp:"At rest, most open channels are K⁺ leak channels. K⁺ flows OUT down its concentration gradient (maintained by Na⁺/K⁺-ATPase), leaving impermeant anions → negative interior. Na⁺/K⁺-ATPase contributes only ~-3 mV directly." },
        { q:"During the absolute refractory period of an action potential, a second AP cannot be generated because:",
          choices:["Na⁺ channels are in the inactivated state (h-gate closed), unresponsive to depolarization","Excessive K⁺ efflux has hyperpolarized the membrane","The Na⁺/K⁺-ATPase is actively resetting ion gradients","Cl⁻ influx is blocking membrane depolarization"], correct:0,
          exp:"After opening, voltage-gated Na⁺ channels inactivate (h-gate closes) within milliseconds. The inactivated state cannot open regardless of stimulus. The membrane must repolarize to allow recovery from inactivation." },
        { q:"Long-term potentiation (LTP) at hippocampal synapses requires NMDA receptor activation because NMDA receptors:",
          choices:["Are solely responsible for all excitatory transmission","Are both ligand-gated AND voltage-gated (Mg²⁺ block removed by depolarization), allowing Ca²⁺ influx that triggers synaptic strengthening","Directly activate CaMKII without Ca²⁺ influx","Have higher affinity for glutamate than AMPA receptors"], correct:1,
          exp:"NMDA receptors require BOTH glutamate binding AND postsynaptic depolarization (to remove Mg²⁺ block) → Ca²⁺ influx → CaMKII activation → AMPA receptor insertion. Coincidence detection = cellular basis of Hebbian learning." },
        { q:"The Nernst equation for K⁺ with [K⁺]in=140mM and [K⁺]out=4mM at 37°C gives E_K ≈:",
          choices:["-35 mV","-94 mV","+94 mV","-55 mV"], correct:1,
          exp:"E_K = (26.7mV) × ln(4/140) = 26.7 × (-3.56) ≈ -95 mV. The resting potential (-70mV) is between E_K (-94) and E_Na (+60), weighted by relative conductances." },
        { q:"Myelination increases conduction velocity by:",
          choices:["Increasing the Na⁺ channel density along the axon","Increasing membrane thickness → reducing capacitance → faster local current spread between nodes of Ranvier (saltatory conduction)","Increasing axoplasm resistance","Adding potassium leak channels at the nodes"], correct:1,
          exp:"Myelin dramatically increases effective membrane thickness (d), reducing capacitance C = ε₀εA/d. Lower capacitance means less charge needed to depolarize the membrane → faster current spread between nodes → saltatory conduction." },
        { q:"Horner's syndrome (ptosis, miosis, anhidrosis) results from disruption of the:",
          choices:["Parasympathetic pathway from CN III to dilator pupillae","Sympathetic pathway from hypothalamus through C8-T2, superior cervical ganglion to the face and eye","Motor pathway from frontal eye fields to CN VI nucleus","Optic nerve causing visual field defect with pupillary sparing"], correct:1,
          exp:"Horner's syndrome = disruption of 3-neuron sympathetic chain: 1st neuron (hypothalamus → C8-T2 lateral horn); 2nd neuron (T1 loops over lung apex → superior cervical ganglion); 3rd neuron (along carotid → dilator pupillae, superior tarsal, facial sweat glands). Causes: Pancoast tumor, carotid dissection, lateral medullary syndrome." },
        { q:"A patient has weakness of the right arm, right leg, and right lower face with forehead sparing. This localizes to:",
          choices:["Right motor cortex (weakness would be ipsilateral)","Left internal capsule or motor cortex (contralateral hemiplegia; forehead sparing indicates upper motor neuron lesion)","Right facial nerve (CN VII) peripherally","Left cerebellum"], correct:1,
          exp:"UMN facial weakness spares the forehead (bilateral cortical representation of forehead). Lesion above the left facial nucleus → contralateral right face (lower), arm, and leg weakness. Left internal capsule or cortex (MCA territory) is the classic location." },
        { q:"Broca's aphasia is characterized by:",
          choices:["Fluent speech with poor comprehension","Non-fluent, effortful speech with relatively preserved comprehension","Inability to repeat despite normal speech and comprehension","Complete loss of all language modalities"], correct:1,
          exp:"Broca's area (left inferior frontal gyrus): speech production. Broca's aphasia: non-fluent, telegraphic, effortful speech; preserved comprehension; poor repetition. Patients are aware and often frustrated. Wernicke's aphasia: fluent, paraphasic, poor comprehension." },
      ]
    },
    {
      id:"physio_005", title:"Endocrinology", difficulty:"Hard", time:480, icon:"🔬",
      questions:[
        { q:"Cortisol causes hyperglycemia by:",
          choices:["Directly inhibiting insulin secretion from β-cells","Stimulating gluconeogenesis, inhibiting peripheral glucose uptake, and causing insulin resistance","Increasing glucagon secretion exclusively","Inhibiting glycogen synthase only"], correct:1,
          exp:"Cortisol: increases hepatic gluconeogenesis (induces PEPCK, G6Pase); inhibits glucose uptake in muscle/fat (decreased GLUT4 translocation); causes protein catabolism providing gluconeogenic precursors. Chronic Cushing's → steroid-induced diabetes." },
        { q:"PTH's effects on bone and kidney include:",
          choices:["Increases bone resorption and increases renal Ca²⁺ reabsorption while decreasing phosphate reabsorption","Decreases bone resorption and promotes calcium deposition in bone","Decreases renal 1-α hydroxylase activity, reducing vitamin D activation","Increases renal phosphate reabsorption causing hyperphosphatemia"], correct:0,
          exp:"PTH: bone (↑osteoclast activity via RANKL → Ca²⁺ + PO₄³⁻ release); kidney (↑Ca²⁺ reabsorption in distal tubule; ↓phosphate reabsorption → phosphaturia; ↑1-α-hydroxylase → active vitamin D). Net: ↑serum Ca²⁺, ↓serum PO₄³⁻." },
        { q:"Diabetes insipidus presents with polyuria and polydipsia with:",
          choices:["Concentrated urine (high osmolality) and high serum ADH","Dilute urine (low osmolality) with either absent ADH (central DI) or ADH resistance (nephrogenic DI)","High serum glucose causing osmotic diuresis","Hypoaldosteronism causing sodium wasting"], correct:1,
          exp:"Central DI: ADH deficiency → cannot concentrate urine. Nephrogenic DI: ADH present but collecting duct unresponsive. Distinguish: desmopressin concentrates urine in central DI but NOT nephrogenic DI." },
        { q:"Primary adrenal insufficiency (Addison's) presents with hyperpigmentation because:",
          choices:["Cortisol directly stimulates melanocytes","Low cortisol → high ACTH (and α-MSH, from POMC) → MSH receptor stimulation → melanocyte activation → hyperpigmentation","High DHEA directly causes melanin synthesis","Adrenal destruction causes bile pigment accumulation"], correct:1,
          exp:"POMC is precursor for both ACTH and α-MSH. In Addison's: low cortisol → high CRH → high POMC → high ACTH AND α-MSH → MC1R on melanocytes → increased melanin. Secondary adrenal insufficiency (low ACTH) has NO hyperpigmentation." },
        { q:"In type 2 diabetes mellitus, the pathophysiology involves:",
          choices:["Autoimmune destruction of β-cells causing absolute insulin deficiency","Peripheral insulin resistance combined with progressive β-cell exhaustion and relative insulin insufficiency","Primary glucagon excess without insulin abnormality","Absolute glucokinase deficiency in hepatocytes"], correct:1,
          exp:"T2DM: initially, peripheral insulin resistance is compensated by β-cell hypersecretion. Over time, β-cells exhaust (ER stress, lipotoxicity, glucotoxicity, amyloid) → relative insulin deficiency. Liver continues hepatic glucose production despite high insulin." },
        { q:"Metformin's primary mechanism involves:",
          choices:["Stimulating insulin secretion from pancreatic β-cells","Activating AMPK → inhibiting hepatic gluconeogenesis and improving insulin sensitivity","Inhibiting α-glucosidase to reduce glucose absorption","Binding PPAR-γ to improve adipocyte insulin sensitivity"], correct:1,
          exp:"Metformin activates AMPK (by inhibiting Complex I → AMP/ATP ratio ↑). AMPK → reduces PEPCK and G6Pase transcription → decreased hepatic glucose output. Weight neutral, no hypoglycemia, reduces CV events. Contraindicated in renal failure." },
        { q:"Graves' disease causes hyperthyroidism through:",
          choices:["Toxic thyroid adenoma producing thyroid hormone autonomously","TSH-receptor stimulating antibodies (TRAb) that mimic TSH and constitutively activate thyroid hormone production","Increased TSH secretion from a pituitary adenoma","Inflammatory release of stored thyroid hormone without new synthesis"], correct:1,
          exp:"Graves' disease: IgG antibodies against TSH receptor (TRAb) activate the receptor → thyroid hormone synthesis + thyroid growth (diffuse goiter). TSH is suppressed by negative feedback. Classic: diffuse goiter, ophthalmopathy, pretibial myxedema." },
        { q:"Hashimoto's thyroiditis is primarily mediated by:",
          choices:["Type I hypersensitivity (IgE-mediated mast cell degranulation)","Type IV (T-cell mediated) and Type II (antibody-mediated) immune reactions against thyroid antigens (anti-TPO, anti-thyroglobulin)","Type III hypersensitivity (immune complex deposition)","Molecular mimicry by bacterial proteins"], correct:1,
          exp:"Hashimoto's: CD4+ T cells infiltrate thyroid → cytokine-mediated follicular destruction (Type IV) PLUS anti-TPO and anti-thyroglobulin antibodies (Type II) → hypothyroidism. Most common cause of hypothyroidism in iodine-sufficient countries." },
      ]
    },
    {
      id:"physio_006", title:"Gastrointestinal Physiology", difficulty:"Hard", time:480, icon:"🫶",
      questions:[
        { q:"Cholecystokinin (CCK) is released from I-cells of the duodenum in response to:",
          choices:["Glucose in the duodenal lumen","Fat and protein (amino acids) in the duodenal lumen","Acid entering the duodenum","Distension of the stomach"], correct:1,
          exp:"CCK released by fat and amino acids in the duodenum: stimulates gallbladder contraction (bile secretion), pancreatic enzyme secretion, slows gastric emptying, promotes satiety. Activates vagal afferents for satiety signaling." },
        { q:"Intrinsic factor (IF) is produced by gastric parietal cells and is required for:",
          choices:["Pepsin activation in the stomach","Absorption of vitamin B12 in the terminal ileum","Bile acid recycling in the jejunum","Iron absorption in the duodenum"], correct:1,
          exp:"IF binds vitamin B12 (cobalamin) in the stomach/duodenum. IF-B12 complex is absorbed by cubilin receptors in the terminal ileum. Pernicious anemia: autoimmune destruction of parietal cells → IF deficiency → B12 malabsorption → megaloblastic anemia + subacute combined degeneration." },
        { q:"The migrating motor complex (MMC) in the fasting state serves to:",
          choices:["Maximize nutrient absorption between meals","Sweep residual food, bacteria, and debris from the small intestine into the colon ('intestinal housekeeper')","Stimulate bile secretion continuously","Regulate gastric acid secretion between meals"], correct:1,
          exp:"MMC: cyclic motor pattern in the fasting state (~90-minute cycles) that migrates from stomach to terminal ileum. Motilin (from M-cells) initiates MMC. Prevents bacterial overgrowth and clears indigestible material. Disrupted by food intake." },
        { q:"Bile acids are amphipathic and facilitate fat absorption by:",
          choices:["Directly hydrolyzing triglycerides in the intestinal lumen","Forming mixed micelles with dietary fat, monoglycerides, and lysophospholipids that facilitate diffusion to the brush border","Activating pancreatic lipase at the brush border","Increasing intestinal motility to improve fat contact time"], correct:1,
          exp:"Bile acids (emulsification + micelle formation): monoglycerides, fatty acids, cholesterol, and fat-soluble vitamins are incorporated into mixed micelles. These allow diffusion to the unstirred water layer and brush border for absorption. Bile acid deficiency → steatorrhea." },
        { q:"Secretin is released from S-cells of the duodenum in response to:",
          choices:["Fat in the duodenum","Protein (amino acids) in the duodenum","Acidic chyme (low pH) entering the duodenum from the stomach","Distension of the duodenum by food"], correct:2,
          exp:"Secretin: released when acid (low pH) enters the duodenum → stimulates pancreatic HCO₃⁻ secretion (to neutralize acid) → inhibits gastric acid secretion and gastric emptying. The 'physiological antacid.' Also stimulates bile secretion." },
        { q:"H. pylori infection causes peptic ulcer disease by all of the following EXCEPT:",
          choices:["Urease producing ammonia that disrupts mucus layer","VacA toxin causing vacuolation and apoptosis of epithelial cells","Increasing prostaglandin synthesis that strengthens the mucosal barrier","CagA virulence factor disrupting epithelial tight junctions and signaling"], correct:2,
          exp:"H. pylori REDUCES prostaglandin-mediated protection (by damaging the mucosa and triggering inflammation that indirectly disrupts PGE₂-mediated mucus/HCO₃⁻ secretion). It does not increase prostaglandins. All other mechanisms (urease, VacA, CagA, LPS) contribute to ulcer pathogenesis." },
        { q:"In iron absorption, dietary iron must be reduced from Fe³⁺ to Fe²⁺ by:",
          choices:["Transferrin in the duodenal lumen","Duodenal cytochrome b (Dcytb) on the brush border of duodenal enterocytes","Hepcidin secreted by the liver","Ceruloplasmin in the plasma"], correct:1,
          exp:"Dcytb (ferrireductase) on the apical surface of duodenal enterocytes converts Fe³⁺ → Fe²⁺, which is then transported into the cell by DMT1. Fe²⁺ crosses the basolateral membrane via ferroportin (regulated by hepcidin) and is oxidized back to Fe³⁺ for transferrin binding." },
        { q:"Zollinger-Ellison syndrome is caused by a gastrinoma producing excess gastrin, which leads to:",
          choices:["Decreased stomach acid production causing malabsorption","Massively increased gastric acid secretion → peptic ulcers in unusual locations (jejunum), diarrhea from acid inactivating pancreatic enzymes","Increased somatostatin from D-cells opposing gastrin","Reduced CCK secretion causing gallstone formation"], correct:1,
          exp:"ZES: gastrin-secreting tumor (usually in the pancreas or duodenum, often malignant; associated with MEN1) → massive gastric acid hypersecretion → multiple peptic ulcers (including jejunal), secretory diarrhea, steatorrhea (acid inactivates lipase), esophagitis. Treated with high-dose PPIs ± surgical resection." },
      ]
    },
  ],

  mcat_mixed: [
    {
      id:"mixed_001", title:"MCAT Full-Length: Block 1", difficulty:"Hard", time:600, icon:"📝",
      questions:[
        { q:"A researcher finds that a drug increases intracellular cAMP levels in liver cells, leading to increased glycogenolysis. Which receptor type does this drug most likely activate?",
          choices:["Ligand-gated ion channel","Receptor tyrosine kinase","Gs-protein coupled receptor","Nuclear receptor"], correct:2,
          exp:"cAMP is produced by adenylyl cyclase, which is activated by Gsα. GPCR activation of Gs → adenylyl cyclase → cAMP → PKA → phosphorylation of glycogen phosphorylase kinase → glycogen phosphorylase activation → glycogenolysis. Classic glucagon/epinephrine mechanism in liver." },
        { q:"In a cross-sectional study, prevalence of hypertension is found to be 40% in adults over 65 versus 15% in adults aged 30-45. The most valid conclusion is:",
          choices:["Aging causes hypertension","Prevalence of hypertension is significantly associated with older age in this population at this point in time","Adults over 65 should all receive antihypertensive medication","Hypertension is primarily a genetic disease in older populations"], correct:1,
          exp:"Cross-sectional studies measure prevalence at a single time point and can identify associations but CANNOT establish causation (no temporal relationship, survivorship bias, confounders). The valid conclusion is the association statement, not a causal claim." },
        { q:"A patient with a tumor in the posterior pituitary would most likely present with:",
          choices:["Gigantism from excess GH","Central diabetes insipidus from ADH deficiency","Cushing's disease from excess ACTH","Hyperprolactinemia from a prolactinoma"], correct:1,
          exp:"The posterior pituitary stores and releases ADH (vasopressin) and oxytocin (both produced in the hypothalamus). A tumor compressing or destroying the posterior pituitary → ADH deficiency → central diabetes insipidus (polyuria, dilute urine, polydipsia)." },
        { q:"Which of the following laboratory findings is most consistent with iron-deficiency anemia?",
          choices:["High serum ferritin, low TIBC, macrocytic RBCs","Low serum ferritin, high TIBC, microcytic hypochromic RBCs","Normal ferritin, normal TIBC, normocytic normochromic RBCs","High serum iron, low TIBC, ringed sideroblasts on bone marrow"], correct:1,
          exp:"Iron deficiency: decreased iron stores → low ferritin (most sensitive early marker); increased transferrin (TIBC) as the body upregulates iron-binding capacity; microcytic, hypochromic RBCs (less Hb synthesis); low serum iron; low % transferrin saturation." },
        { q:"A molecule with the formula C₅H₈O has 2 degrees of unsaturation (DBE). Which structure is most consistent with this formula and a strong IR absorption at ~1740 cm⁻¹?",
          choices:["A five-membered ring with no carbonyl","A cyclopentanone (cyclic ketone)","An open-chain diene (two C=C)","An aromatic furan ring"], correct:1,
          exp:"DBE = (2×5 + 2 - 8)/2 = 2. Carbonyl at ~1740 cm⁻¹ (ester or cyclic ketone). Cyclopentanone has one ring (1 DBE) + one C=O (1 DBE) = 2 DBE and fits C₅H₈O with a ketone carbonyl at ~1740 cm⁻¹." },
        { q:"Sympathetic stimulation of the heart increases heart rate by:",
          choices:["Hyperpolarizing the SA node by opening K⁺ channels","Activating β₁-adrenergic receptors → cAMP → PKA → phosphorylation of HCN (funny) channels, speeding diastolic depolarization","Directly opening L-type Ca²⁺ channels in the SA node","Inhibiting the parasympathetic ganglia in the heart"], correct:1,
          exp:"β₁-AR → Gs → cAMP → PKA → HCN channels (If, pacemaker current) phosphorylation → increased If current → faster diastolic depolarization (steeper slope) → shorter time to threshold → increased HR (positive chronotropy). PKA also phosphorylates L-type Ca²⁺ channels (positive inotropy)." },
        { q:"A study measures the association between cell phone use and brain cancer. An odds ratio of 1.02 (95% CI: 0.78-1.34) is found. The most appropriate conclusion is:",
          choices:["Cell phones significantly increase brain cancer risk","Cell phone use is strongly protective against brain cancer","No statistically significant association between cell phone use and brain cancer was found (CI includes 1.0)","The study is too small and the OR should be recalculated"], correct:2,
          exp:"The 95% CI includes 1.0 (no association), meaning the result is not statistically significant. An OR of 1.02 is very close to the null (no association). Even if statistically significant, an OR of 1.02 would represent negligible clinical effect. Correct interpretation: no significant association found." },
        { q:"A patient has been given a drug that blocks acetylcholinesterase. The expected effects include:",
          choices:["Dry mouth, dilated pupils, tachycardia (anticholinergic effects)","Excessive salivation, bradycardia, miosis, bronchospasm (cholinergic excess)","Hypertension and mydriasis from sympathomimetic effect","Decreased intestinal motility and urinary retention"], correct:1,
          exp:"AChE inhibitors → acetylcholine accumulates at muscarinic (SLUD: Salivation, Lacrimation, Urination, Defecation, plus bradycardia, bronchoconstriction, miosis) and nicotinic synapses (muscle fasciculations, weakness). Opposite of anticholinergic effects." },
      ]
    },
    {
      id:"mixed_002", title:"MCAT Full-Length: Block 2", difficulty:"Hard", time:600, icon:"📋",
      questions:[
        { q:"Hardy-Weinberg equilibrium requires all of the following EXCEPT:",
          choices:["Large population size","Random mating","Strong directional natural selection","No migration into or out of the population"], correct:2,
          exp:"HWE requires: large population, random mating, no mutation, no migration, NO natural selection. Strong directional selection would change allele frequencies, violating HWE. It serves as the null model; deviations indicate evolutionary forces are acting." },
        { q:"Which of the following is the best example of a randomized controlled trial (RCT)?",
          choices:["Comparing cancer rates in smokers vs. non-smokers over 20 years (cohort study)","Randomly assigning patients to receive a new drug or placebo and measuring outcomes (RCT)","Surveying patients about past exposure to determine current disease rates (case-control)","Measuring the prevalence of obesity in different countries at a single time point"], correct:1,
          exp:"RCT: researchers randomly assign participants to intervention vs. control groups. Random assignment controls for confounding (known and unknown). RCTs provide the strongest evidence for causation. The described study matches this definition precisely." },
        { q:"A child with recurrent bacterial infections, absent lymph nodes, and undetectable immunoglobulins of all classes most likely has:",
          choices:["DiGeorge syndrome (T cell deficiency)","X-linked agammaglobulinemia (Bruton's disease — BTK mutation, absent B cells)","SCID (combined T and B cell deficiency)","Selective IgA deficiency"], correct:1,
          exp:"Bruton's XLA: BTK mutation → B cell development arrests at pre-B cell stage → no mature B cells → no immunoglobulins (all classes) → susceptibility to encapsulated bacteria after maternal antibodies wane (~6 months). No lymph nodes/tonsils (no B cell follicles). Treated with IVIG." },
        { q:"A 55-year-old man develops left flank pain radiating to the groin, hematuria, and nausea. Plain X-ray shows a 5mm opacity at the ureterovesical junction. The most likely composition of this stone is:",
          choices:["Uric acid (radiolucent, not seen on plain X-ray)","Calcium oxalate or calcium phosphate (most common, radiopaque, visible on X-ray)","Struvite (magnesium ammonium phosphate, associated with urease-producing bacteria)","Cystine stone (associated with cystinuria, weakly radiopaque)"], correct:1,
          exp:"~80% of kidney stones are calcium-containing (oxalate or phosphate) and are radiopaque on plain X-ray. Uric acid stones are radiolucent (not seen on plain X-ray but visible on CT). Classic presentation: colicky flank-to-groin pain ('renal colic'), hematuria." },
        { q:"Which of the following best describes the mechanism of action of β-lactam antibiotics?",
          choices:["Inhibit the 30S ribosomal subunit, blocking protein synthesis","Inhibit cell wall synthesis by covalently binding penicillin-binding proteins (transpeptidases), preventing peptidoglycan cross-linking","Disrupt bacterial cell membrane integrity by acting as detergents","Inhibit RNA polymerase, blocking transcription"], correct:1,
          exp:"β-Lactams (penicillins, cephalosporins, carbapenems): covalently bind PBPs (transpeptidases) that cross-link the peptidoglycan cell wall. Without cross-linking, the cell wall weakens and bacteria lyse under osmotic pressure. Bacterial β-lactamases hydrolyze the β-lactam ring, conferring resistance." },
        { q:"Which of the following is the correct order of events in the complement classical pathway?",
          choices:["C3 spontaneous hydrolysis → Bb → C3b → MAC","C1q binds antibody-antigen complex → C4 and C2 cleavage → C3 convertase → C5 convertase → MAC","Mannose-binding lectin → MASP → C3b → C5b → MAC","Properdin stabilizes C3bBb → classical pathway C3 convertase → MAC"], correct:1,
          exp:"Classical pathway sequence: IgG/IgM + antigen → C1q binding → C1r/C1s activation → C4 cleavage (C4a + C4b) → C4b binds antigen + C2 cleavage → C4b2a (C3 convertase) → C3 cleavage → C4b2a3b (C5 convertase) → C5b → MAC (C5b-9). Lectin pathway: MBL replaces C1q." },
        { q:"A 30-year-old woman has cyclical mastalgia and fibrocystic breast changes. FSH and LH are normal. Which hormone is most directly responsible for the cyclical breast changes?",
          choices:["Prolactin (promotes milk production)","Estrogen and progesterone cycling during the menstrual cycle","Oxytocin (promotes milk letdown)","Cortisol (causes breast tissue inflammation)"], correct:1,
          exp:"Fibrocystic breast changes (most common benign breast condition): cyclical pain/tenderness correlating with menstrual cycle. Estrogen stimulates ductal proliferation; progesterone promotes lobular development. Cyclical variation in these hormones drives cyclical breast changes. Worse in the luteal phase (high progesterone)." },
        { q:"The sodium-glucose cotransporter (SGLT2) in the proximal tubule reabsorbs glucose with sodium. SGLT2 inhibitors (gliflozins) lower blood glucose by:",
          choices:["Stimulating insulin secretion from β-cells","Preventing renal glucose reabsorption, causing glucosuria and lowering plasma glucose","Increasing glucose uptake in peripheral muscle","Inhibiting hepatic gluconeogenesis via AMPK"], correct:1,
          exp:"SGLT2 (in the S1 segment of PCT) reabsorbs ~90% of filtered glucose. Gliflozins block SGLT2 → glucosuria → lower plasma glucose. Bonus effects: osmotic diuresis → reduced blood pressure; weight loss; reduced intraglomerular pressure (cardioprotective, renoprotective). Used in T2DM, heart failure, CKD." },
      ]
    },
    {
      id:"mixed_003", title:"MCAT Full-Length: Block 3", difficulty:"Hard", time:600, icon:"🎓",
      questions:[
        { q:"A decrease in alveolar ventilation (hypoventilation) will cause:",
          choices:["Decreased PaCO₂ and increased PaO₂","Increased PaCO₂ and decreased PaO₂ (respiratory acidosis)","Increased PaO₂ with normal PaCO₂","Metabolic alkalosis with compensatory hyperventilation"], correct:1,
          exp:"Alveolar ventilation removes CO₂. Hypoventilation → CO₂ accumulates → PaCO₂ ↑ → respiratory acidosis (pH↓). By the alveolar gas equation, ↑PaCO₂ displaces O₂ → PaO₂ ↓ (hypoxemia). This is the mechanism in hypoventilation from opioids, CNS depression, or severe obstructive lung disease." },
        { q:"A 45-year-old woman with rheumatoid arthritis is started on methotrexate. The mechanism of action is:",
          choices:["Blocking TNF-α to reduce inflammation","Inhibiting dihydrofolate reductase (DHFR), reducing THF levels and impairing rapidly dividing immune cells (also blocks purine and thymidylate synthesis)","Blocking IL-6 receptor signaling","Depleting CD20+ B cells via antibody-dependent cytotoxicity"], correct:1,
          exp:"Methotrexate: competitive inhibitor of DHFR (requires folate analog resemblance). Low DHFR activity → less THF → impaired thymidylate synthesis (dTMP) and purine synthesis → decreased DNA synthesis in rapidly dividing cells (synovial fibroblasts, lymphocytes). Also has anti-inflammatory effects via adenosine pathway." },
        { q:"In gel electrophoresis, proteins are separated based on size using SDS-PAGE. SDS (sodium dodecyl sulfate) is added because it:",
          choices:["Precipitates proteins by ionic interactions","Denatures proteins and coats them with negative charge proportional to mass, so all migrate toward the anode based on size alone","Reduces disulfide bonds to separate subunits","Cross-links proteins to stabilize their native structure during migration"], correct:1,
          exp:"SDS is an anionic detergent that: (1) denatures proteins (destroys non-covalent structure); (2) binds uniformly to protein backbone (~1.4 g SDS per g protein) coating all proteins with negative charge proportional to mass. In a polyacrylamide gel under electric field, all proteins migrate toward anode (+) at rates determined solely by molecular weight (size)." },
        { q:"A man with Klinefelter syndrome (47,XXY) most commonly presents with:",
          choices:["Ambiguous genitalia at birth","Tall stature, small testes (hypogonadism), infertility, and often gynecomastia","Turner syndrome features (short stature, webbed neck, aortic coarctation)","Intellectual disability as the primary presenting feature"], correct:1,
          exp:"Klinefelter (47,XXY): most common sex chromosome aneuploidy in males (1/500-1000 male births). Features: tall stature (long legs), small/firm testes, azoospermia (infertility), gynecomastia, decreased testosterone, elevated FSH/LH, learning difficulties (variable). Often diagnosed during infertility workup. Treatment: testosterone replacement." },
        { q:"A researcher performs PCR using primers flanking a region of interest. If the initial template contains 100 copies of the target sequence, how many copies will be present after 10 cycles?",
          choices:["1,000 copies","102,400 copies","10,000 copies","204,800 copies"], correct:1,
          exp:"PCR doubles the template with each cycle: copies = initial × 2^n = 100 × 2^10 = 100 × 1024 = 102,400. Note: the first few cycles produce long products; exponential amplification of the specific target segment begins from cycle 3. Each cycle: denaturation → annealing → extension." },
        { q:"The conversion of prothrombin to thrombin is catalyzed by factor Xa in the presence of factor Va, phospholipid, and Ca²⁺ (prothrombinase complex). This represents which step in hemostasis?",
          choices:["Primary hemostasis (platelet plug formation)","Secondary hemostasis (coagulation cascade) — the common pathway","Fibrinolysis (clot dissolution)","Anticoagulation via protein C and S pathway"], correct:1,
          exp:"Prothrombinase complex (Xa + Va + phospholipid + Ca²⁺) converts prothrombin (II) → thrombin (IIa). This is the key step where the extrinsic (TF-VIIa) and intrinsic (VIIIa-IXa) pathways converge in the COMMON PATHWAY of the coagulation cascade. Thrombin then converts fibrinogen → fibrin and activates platelets." },
        { q:"Which of the following mutations would most likely increase an enzyme's Km without affecting Vmax?",
          choices:["A mutation in the enzyme's catalytic residues that reduces kcat","A mutation at the substrate-binding site that weakens substrate affinity (increases dissociation constant, Kd)","A mutation that reduces enzyme expression by 50%","A mutation that causes the enzyme to form inactive aggregates"], correct:1,
          exp:"Km ≈ Kd for the ES complex when kcat << k-1. A mutation reducing binding affinity (weaker non-covalent interactions between substrate and active site residues) increases Kd ≈ Km. If the catalytic residues are unaffected, kcat and Vmax are preserved. This creates apparent competitive inhibitor-like kinetics (same Vmax, higher Km)." },
        { q:"Social facilitation theory (Zajonc) predicts that the presence of others:",
          choices:["Always improves performance on any task","Improves performance on well-learned (simple) tasks and impairs performance on novel (complex) tasks","Impairs performance on all tasks due to distraction","Only affects performance when the others are experts in the same field"], correct:1,
          exp:"Zajonc's social facilitation: presence of others increases arousal/drive. For well-learned (dominant) responses, arousal → facilitation (improved performance). For novel or complex tasks, the dominant response is often incorrect → arousal → impaired performance. Explains athlete performance in front of crowds vs. learning a new skill publicly." },
      ]
    },
    {
      id:"mixed_004", title:"MCAT Biochemistry & Molecular", difficulty:"Hard", time:600, icon:"⚗️",
      questions:[
        { q:"Transcription factors that bind GC-rich promoter sequences and activate transcription in response to hypoxia include:",
          choices:["p53 (tumor suppressor activated by DNA damage)","HIF-1α (hypoxia-inducible factor, stabilized when PHD enzymes are inhibited under low O₂)","NF-κB (activated by inflammatory signals)","STAT3 (activated by JAK kinases in cytokine signaling)"], correct:1,
          exp:"HIF-1α is constitutively transcribed but continuously hydroxylated by PHD enzymes (prolyl hydroxylases, requiring O₂) → VHL-mediated ubiquitination → proteasomal degradation. Under hypoxia: PHD inactive → HIF-1α accumulates → dimerizes with HIF-1β → binds HREs → activates VEGF, EPO, glycolytic genes, GLUT1/3." },
        { q:"Which of the following base pairings is found in Watson-Crick double-stranded DNA?",
          choices:["Adenine-Cytosine (2 hydrogen bonds)","Guanine-Cytosine (3 hydrogen bonds) and Adenine-Thymine (2 hydrogen bonds)","Guanine-Thymine (3 hydrogen bonds)","Adenine-Uracil (2 hydrogen bonds, found in DNA-RNA hybrids only)"], correct:1,
          exp:"Watson-Crick base pairing in DNA: A-T (2 H-bonds, Adenine pairs with Thymine); G-C (3 H-bonds, Guanine pairs with Cytosine). In RNA-DNA hybrids (replication/transcription): A-U (RNA) pairs with A in RNA opposite T in DNA template. G-C always has 3 H-bonds, A-T has 2." },
        { q:"The regulation of eukaryotic gene expression differs from prokaryotic regulation because eukaryotes primarily regulate at the level of:",
          choices:["Attenuation (coupled transcription-translation)","Multiple levels including chromatin remodeling, transcription initiation, mRNA processing, nuclear export, translation, and post-translational modification","Riboswitches in 5'UTR of mRNA","Sigma factor switching to regulate sets of genes"], correct:1,
          exp:"Eukaryotic gene regulation is multilevel: chromatin remodeling (histone modifications, DNA methylation, nucleosome positioning), transcription initiation (transcription factors, enhancers), mRNA processing (splicing, 5' cap, polyA), nuclear export, mRNA stability, translation control, post-translational modifications. Prokaryotes use operons, attenuation, riboswitches." },
        { q:"A missense mutation changes an arginine codon (CGG) to serine (AGG is actually Arg; Ser would be AGC/AGT/TCN). The mutation Arg→Gln (conservative) would be LEAST likely to affect enzyme function if the arginine is:",
          choices:["In the active site forming a salt bridge with the substrate","On the protein surface far from the active site (structurally non-critical)","Part of the hydrophobic core maintaining tertiary structure","Required for disulfide bond formation"], correct:1,
          exp:"Mutations at surface residues far from the active site and not involved in protein-protein interactions tend to be the most tolerated (often synonymous in terms of function even if non-synonymous at the sequence level). Surface positions are subject to less evolutionary constraint than active site, buried hydrophobic core, or structurally critical residues." },
        { q:"The sodium-potassium ATPase (Na⁺/K⁺-ATPase) is classified as a P-type ATPase. The 'P' designation refers to:",
          choices:["The fact that it pumps phosphate ions","Formation of a phosphorylated intermediate (aspartyl-phosphate) during the catalytic cycle","Its location in the plasma membrane","The requirement for a protein co-factor to function"], correct:1,
          exp:"P-type ATPases form a covalent phosphorylated (aspartyl) intermediate during the transport cycle. This includes Na⁺/K⁺-ATPase, Ca²⁺-ATPase (SERCA), H⁺/K⁺-ATPase (gastric parietal cells). V-type (vacuolar): proton pumps in lysosomes/plant vacuoles. F-type: ATP synthase in mitochondria/chloroplasts. ABC transporters: use ATP hydrolysis without phosphorylated intermediate." },
        { q:"Which of the following enzymes is correctly matched with its required cofactor?",
          choices:["Pyruvate carboxylase — pyridoxal phosphate (B6)","Pyruvate dehydrogenase — thiamine pyrophosphate (B1), lipoic acid, FAD, NAD⁺, CoA","Transaminases (ALT/AST) — biotin","Fatty acid synthase — cobalamin (B12)"], correct:1,
          exp:"PDH complex requires 5 cofactors (mnemonic 'Tender Loving Care For Nancy'): Thiamine PP (B1), Lipoic acid, CoA, FAD (B2), NAD⁺ (B3). Pyruvate carboxylase requires BIOTIN (not B6). Transaminases require PLP (B6). FAS requires NADPH, pantothenic acid (B5 in CoA and ACP), biotin." },
        { q:"CRISPR-Cas9 creates a double-strand break in DNA. When repaired by NHEJ (non-homologous end joining) rather than HDR (homology-directed repair), the typical result is:",
          choices:["Precise single nucleotide correction","Random insertions/deletions (indels) that often cause frameshift mutations","Chromosomal translocations exclusively","Silencing without sequence change"], correct:1,
          exp:"NHEJ (predominant in G1/quiescent cells) is error-prone, producing small indels at the cut site. If in a coding exon, indels frequently cause frameshifts → premature stop codon → loss of function (gene knockout). HDR (occurs in S/G2 with a repair template) allows precise editing but is less efficient in most cell types." },
        { q:"The genetic code is said to be 'degenerate.' This means:",
          choices:["Many codons lack amino acid assignments and cause frameshift mutations","Multiple codons can specify the same amino acid (synonymous codons), especially differing at the third codon position (wobble position)","The code has changed over the course of evolution in different species","The ribosome frequently makes errors in decoding mRNA"], correct:1,
          exp:"Degeneracy: 64 codons encode only 20 amino acids + 3 stop codons. Most amino acids are encoded by multiple synonymous codons (e.g., Leu: 6 codons; Ser: 6 codons; Gly: 4 codons). Synonymous substitutions at the wobble (3rd) position are common and often silent (don't change amino acid). This degeneracy buffers against mutation effects." },
      ]
    },
    {
      id:"mixed_005", title:"MCAT Psychology & Sociology", difficulty:"Medium", time:600, icon:"🧬",
      questions:[
        { q:"According to Maslow's hierarchy of needs, which level must generally be satisfied before an individual can focus on belongingness and love needs?",
          choices:["Esteem needs (confidence, achievement)","Safety needs (security, stability)","Self-actualization (achieving full potential)","Cognitive needs (knowledge, understanding)"], correct:1,
          exp:"Maslow's hierarchy (bottom to top): Physiological → Safety → Belongingness/Love → Esteem → Self-actualization. Safety needs (security, stability, freedom from fear) must be addressed before belongingness needs motivate behavior. This is a deficiency (D-need) hierarchy." },
        { q:"The bystander effect is REDUCED in which situation?",
          choices:["When there are many witnesses to the emergency","When the bystander is alone with the victim (no diffusion of responsibility)","When all bystanders are strangers to each other","When the situation is ambiguous and unclear if an emergency is occurring"], correct:1,
          exp:"Bystander effect: more bystanders → less likely any individual helps (diffusion of responsibility + pluralistic ignorance). Reduced when: (1) only one bystander present (no diffusion); (2) bystanders know each other; (3) situation is clearly an emergency (less pluralistic ignorance); (4) bystanders have relevant expertise." },
        { q:"Which sociological concept explains why individuals from lower socioeconomic backgrounds may internalize dominant social norms that disadvantage their own group?",
          choices:["Conflict theory (economic class exploitation)","Cultural capital (Bourdieu — dominant groups have cultural advantages)","Symbolic interactionism (micro-level meaning-making)","False consciousness (Marx — lower class accepting ideas serving the upper class's interests)"], correct:3,
          exp:"False consciousness (Marx): lower socioeconomic groups internalize dominant ideological norms that justify and perpetuate the existing social hierarchy, even when those norms work against their interests. The ruling class's ideas become the ruling ideas of the epoch. Related to Gramsci's concept of hegemony." },
        { q:"The concept of 'self-fulfilling prophecy' in education is best illustrated by:",
          choices:["Students studying more because they have higher test anxiety","Teachers who expect certain students to perform well giving those students more attention and feedback, leading to better actual performance (Pygmalion effect)","Students choosing harder courses because they have higher self-efficacy","Schools allocating resources based on socioeconomic status of the neighborhood"], correct:1,
          exp:"Pygmalion effect (Rosenthal & Jacobson): teachers' expectancies influence student outcomes. Teachers expecting higher performance: give more encouragement, more complex material, longer wait time for answers, more feedback. Students respond to these differential behaviors → expectation becomes reality (self-fulfilling prophecy)." },
        { q:"Erik Erikson's stage for young adults (ages 18-40) centers on which developmental conflict?",
          choices:["Identity vs. Role Confusion","Intimacy vs. Isolation","Generativity vs. Stagnation","Ego Integrity vs. Despair"], correct:1,
          exp:"Erikson's stages: Adolescence = Identity vs. Role Confusion; Young Adulthood (18-40) = Intimacy vs. Isolation (forming close, committed relationships); Middle Adulthood = Generativity vs. Stagnation (contributing to next generation); Late Adulthood = Ego Integrity vs. Despair (reflecting on life's meaning)." },
        { q:"Which of the following is the best example of a negative reinforcement (operant conditioning)?",
          choices:["A child receives a gold star for completing their homework (positive reinforcement)","A driver fastens their seatbelt to stop the annoying alarm chiming (negative reinforcement — removing aversive stimulus)","A student loses recess privileges for misbehaving (punishment)","A dog receives a treat for sitting on command (positive reinforcement)"], correct:1,
          exp:"Negative reinforcement: REMOVING or avoiding an aversive stimulus INCREASES the probability of a behavior. The seatbelt behavior is reinforced by the removal of the aversive alarm. Confusion: 'negative' ≠ bad/punishment; it means removal. Positive/negative = adding/removing. Reinforcement always increases behavior." },
        { q:"The biopsychosocial model of health (Engel) proposes that illness is best understood as:",
          choices:["Exclusively biological (disease is always organic in origin)","A complex interaction of biological, psychological, and social factors that together determine health and illness","Primarily a social construct defined by cultural norms","Psychological in origin with secondary biological manifestations"], correct:1,
          exp:"Engel's biopsychosocial model (1977): health and illness arise from the interaction of biological factors (genetics, physiology), psychological factors (cognition, emotion, behavior), and social factors (SES, culture, relationships, environment). Contrasts with the biomedical model (disease = biological malfunction only). Foundation of modern medicine, psychiatry, and health psychology." },
        { q:"In Milgram's obedience studies, which factor MOST reduced participant compliance with the experimenter's instructions?",
          choices:["The experimenter wearing a white lab coat","The experiment being conducted at a prestigious institution (Yale)","The learner being visible in the same room as the participant (proximity)","The participant working alone without other participants observing"], correct:2,
          exp:"Milgram found that obedience decreased dramatically when: (1) victim was in the same room as participant (proximity/touch condition: 40% full compliance vs. 65% in remote condition); (2) experimenter left the room; (3) other 'participants' (confederates) refused. The screams and visible suffering made it harder to dehumanize/distance the victim." },
      ]
    },
    {
      id:"mixed_006", title:"MCAT Physics & Chemistry", difficulty:"Hard", time:600, icon:"🔭",
      questions:[
        { q:"A buffer solution is most effective at resisting pH changes when:",
          choices:["The pH is much higher than the pKa of the weak acid","The pH equals the pKa of the weak acid (Henderson-Hasselbalch: equal concentrations of weak acid and conjugate base)","The solution contains a large excess of strong acid","The pH is much lower than the pKa (mostly undissociated acid form present)"], correct:1,
          exp:"Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]). Buffer capacity is maximum when [A⁻] = [HA] → ratio = 1 → log(1) = 0 → pH = pKa. Effective buffering range is approximately pKa ± 1. Blood carbonate buffer (pKa = 6.1) is effective at pH 7.4 because of the open system (CO₂ exhaled maintaining equilibrium)." },
        { q:"Which of the following correctly describes the photoelectric effect?",
          choices:["Increasing light intensity increases the kinetic energy of ejected electrons","A threshold frequency must be exceeded before electrons are ejected, regardless of intensity; KE_max = hf - φ","Electrons are ejected with a time delay proportional to light intensity","Lower frequency light produces more energetic electrons than high-frequency light"], correct:1,
          exp:"Einstein's explanation (Nobel Prize 1921): KE_max = hf - φ (φ = work function = energy to remove an electron). Below threshold frequency (f₀ = φ/h): NO electrons ejected regardless of intensity. Above threshold: KE depends on frequency (not intensity). Intensity determines NUMBER of electrons, not their energy. Proves quantized photons." },
        { q:"Boyle's Law states that at constant temperature, the pressure and volume of an ideal gas are inversely related (P₁V₁ = P₂V₂). A gas compressed from 10L to 2L at 25°C. If initial pressure was 1 atm, final pressure is:",
          choices:["0.2 atm","5 atm","2 atm","10 atm"], correct:1,
          exp:"P₁V₁ = P₂V₂: (1 atm)(10 L) = P₂(2 L) → P₂ = 10/2 = 5 atm. The gas is compressed to 1/5 of its original volume → pressure increases 5-fold. Applies to ideal gases at constant temperature (isothermal process)." },
        { q:"A researcher measures the ΔG° of a reaction and finds it to be +15 kJ/mol. At equilibrium, the reaction:",
          choices:["Has equal concentrations of reactants and products (Keq = 1)","Favors reactants significantly (Keq < 1, since ΔG° = -RT ln Keq, positive ΔG° → Keq < 1)","Proceeds spontaneously under all conditions","Has Keq > 1, favoring products"], correct:1,
          exp:"ΔG° = -RT ln Keq. Positive ΔG° → -RT ln Keq > 0 → ln Keq < 0 → Keq < 1 (equilibrium favors reactants). The reaction is non-spontaneous under standard conditions (but can be made spontaneous by coupling or maintaining Q < Keq). ΔG = 0 at equilibrium (not ΔG° = 0 unless Keq = 1)." },
        { q:"Two waves of equal amplitude and frequency meet in space. When their phase difference is exactly 180°, the result is:",
          choices:["Constructive interference (doubled amplitude)","Destructive interference (zero amplitude)","Beats with a frequency equal to the sum of the two frequencies","No interference because they have equal frequencies"], correct:1,
          exp:"Destructive interference: when two waves of equal amplitude meet with 180° phase difference (half wavelength path difference), they cancel completely → zero amplitude at that point. Constructive interference: 0° phase difference (or 360°, 720°...) → doubled amplitude. Principle used in noise-canceling headphones." },
        { q:"In gel electrophoresis of nucleic acids, which sample would migrate FASTEST toward the anode?",
          choices:["A 5,000 base pair (bp) circular plasmid (supercoiled)","A 500 bp linear DNA fragment","A 50 bp linear DNA oligonucleotide","A 5,000 bp linear DNA fragment"], correct:2,
          exp:"DNA migrates toward the anode (+) because it is negatively charged (phosphate backbone). Smaller fragments migrate FASTER through the gel matrix (less resistance). A 50 bp oligonucleotide is the smallest → fastest migration. Note: supercoiled circular DNA migrates differently from linear DNA of the same size (migrates faster than linear because it's more compact)." },
        { q:"The Henderson-Hasselbalch equation applied to blood buffer: if pKa(H₂CO₃/HCO₃⁻) = 6.1 and [HCO₃⁻] = 24 mEq/L, [H₂CO₃] = 1.2 mEq/L, then blood pH is:",
          choices:["6.1","7.4","7.1","6.8"], correct:1,
          exp:"pH = pKa + log([HCO₃⁻]/[H₂CO₃]) = 6.1 + log(24/1.2) = 6.1 + log(20) = 6.1 + 1.3 = 7.4. This is the normal blood pH. The 20:1 ratio ([HCO₃⁻]:[H₂CO₃]) is maintained by the lungs (CO₂ exhalation) and kidneys (HCO₃⁻ regulation). Respiratory acidosis: ↑CO₂ → ratio ↓ → pH ↓." },
        { q:"Osmolarity differs from molarity in that osmolarity accounts for:",
          choices:["The molecular weight of solute particles","The total number of osmotically active particles in solution (dissociation of electrolytes)","The temperature and pressure of the solution","Only the concentration of non-penetrating solutes"], correct:1,
          exp:"Osmolarity = sum of molar concentrations × osmotic coefficients. For NaCl: 1 mol/L → ~2 Osm/L (Na⁺ + Cl⁻). For glucose (non-dissociating): 1 mol/L = 1 Osm/L. Plasma osmolarity = 2[Na⁺] + [glucose]/18 + [BUN]/2.8 ≈ 285-295 mOsm/L. Drives osmotic water flow (determines tonicity)." },
      ]
    },
  ],
};

export const CATEGORIES = [
  { key:"biochemistry", label:"Biochemistry", icon:"🧪", color:"#3B82F6", description:"Glycolysis, TCA, amino acids, enzymes, DNA, lipids" },
  { key:"physiology", label:"Physiology", icon:"❤️", color:"#EF4444", description:"Cardio, pulmonary, renal, neuro, endo, GI systems" },
  { key:"mcat_mixed", label:"MCAT Full-Length", icon:"📝", color:"#8B5CF6", description:"Mixed passages across all MCAT sections" },
];

export const DIFFICULTY_COLORS = {
  Easy: "#10B981",
  Medium: "#F59E0B",
  Hard: "#EF4444",
};
